-- sqlfluff:ignore:parsing
-- ^ admin/DBA script: GRANT/ALTER ROLE/RESOURCE MONITOR forms are valid SQL that sqlfluff's dialect cannot parse yet.
-- =============================================================================
-- SNOWFLAKE SERVING LAYER — account objects (run as SECURITYADMIN / SYSADMIN)
-- Databricks publishes gold here; Power BI reads from here.
-- =============================================================================

USE ROLE SYSADMIN;

-- Separate warehouses = workload isolation + clean cost attribution.
CREATE WAREHOUSE IF NOT EXISTS WH_MFG_LOAD WITH
  WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Databricks publisher MERGEs (bursty, a few minutes per run)';

CREATE WAREHOUSE IF NOT EXISTS WH_MFG_BI WITH
  WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 3 SCALING_POLICY = 'STANDARD'
  COMMENT = 'Power BI DirectQuery + Import refresh. Multi-cluster absorbs Monday-morning concurrency';

CREATE DATABASE IF NOT EXISTS MFG_DW COMMENT = 'NorthForge manufacturing data warehouse (serving copy of Databricks gold)';
CREATE SCHEMA IF NOT EXISTS MFG_DW.STAGE     WITH MANAGED ACCESS COMMENT = 'Transient change sets written by the Spark connector';
CREATE SCHEMA IF NOT EXISTS MFG_DW.GOLD      WITH MANAGED ACCESS COMMENT = 'Replica of Databricks gold star schema (facts + SCD2 dims)';
CREATE SCHEMA IF NOT EXISTS MFG_DW.REPORTING WITH MANAGED ACCESS COMMENT = 'Business views consumed by Power BI';
CREATE SCHEMA IF NOT EXISTS MFG_DW.SECURITY  WITH MANAGED ACCESS COMMENT = 'Row access policies + entitlement mapping';

-- Resource monitor: a runaway DirectQuery report cannot burn the monthly budget.
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS RM_MFG_BI WITH CREDIT_QUOTA = 300 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND ON 110 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE WH_MFG_BI SET RESOURCE_MONITOR = RM_MFG_BI;

-- ----------------------------------------------------------------------------- RBAC
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS MFG_PUBLISHER_ROLE COMMENT = 'Databricks service user: write STAGE + GOLD';
CREATE ROLE IF NOT EXISTS MFG_BI_READER_ROLE COMMENT = 'Power BI service account / gateway: read GOLD + REPORTING';
CREATE ROLE IF NOT EXISTS MFG_ANALYST_ROLE  COMMENT = 'Ad-hoc analysts: read REPORTING only';
GRANT ROLE MFG_PUBLISHER_ROLE TO ROLE SYSADMIN;
GRANT ROLE MFG_BI_READER_ROLE TO ROLE SYSADMIN;
GRANT ROLE MFG_ANALYST_ROLE  TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE WH_MFG_LOAD TO ROLE MFG_PUBLISHER_ROLE;
GRANT USAGE ON DATABASE MFG_DW TO ROLE MFG_PUBLISHER_ROLE;
GRANT USAGE, CREATE TABLE ON SCHEMA MFG_DW.STAGE TO ROLE MFG_PUBLISHER_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA MFG_DW.STAGE TO ROLE MFG_PUBLISHER_ROLE;
GRANT USAGE ON SCHEMA MFG_DW.GOLD TO ROLE MFG_PUBLISHER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA MFG_DW.GOLD TO ROLE MFG_PUBLISHER_ROLE;

GRANT USAGE ON WAREHOUSE WH_MFG_BI TO ROLE MFG_BI_READER_ROLE;
GRANT USAGE ON DATABASE MFG_DW TO ROLE MFG_BI_READER_ROLE;
GRANT USAGE ON SCHEMA MFG_DW.GOLD TO ROLE MFG_BI_READER_ROLE;
GRANT USAGE ON SCHEMA MFG_DW.REPORTING TO ROLE MFG_BI_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MFG_DW.GOLD TO ROLE MFG_BI_READER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MFG_DW.REPORTING TO ROLE MFG_BI_READER_ROLE;

GRANT USAGE ON WAREHOUSE WH_MFG_BI TO ROLE MFG_ANALYST_ROLE;
GRANT USAGE ON DATABASE MFG_DW TO ROLE MFG_ANALYST_ROLE;
GRANT USAGE ON SCHEMA MFG_DW.REPORTING TO ROLE MFG_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MFG_DW.REPORTING TO ROLE MFG_ANALYST_ROLE;

-- ----------------------------------------------------------------------------- service users (KEY-PAIR auth, no passwords)
-- Private key lives in Azure Key Vault (secret snowflake-publisher-private-key) -> Databricks secret scope.
CREATE USER IF NOT EXISTS SVC_DATABRICKS_PUBLISHER TYPE = SERVICE
  DEFAULT_ROLE = MFG_PUBLISHER_ROLE DEFAULT_WAREHOUSE = WH_MFG_LOAD
  RSA_PUBLIC_KEY = '<paste-public-key-body>' COMMENT = 'Databricks gold -> Snowflake publisher';
GRANT ROLE MFG_PUBLISHER_ROLE TO USER SVC_DATABRICKS_PUBLISHER;

-- Power BI: end users sign in with Entra ID SSO (DirectQuery passes identity -> row access policy applies per user).
-- Scheduled Import refresh uses this service user.
CREATE USER IF NOT EXISTS SVC_POWERBI_REFRESH TYPE = SERVICE
  DEFAULT_ROLE = MFG_BI_READER_ROLE DEFAULT_WAREHOUSE = WH_MFG_BI
  RSA_PUBLIC_KEY = '<paste-public-key-body>' COMMENT = 'Power BI semantic model scheduled refresh';
GRANT ROLE MFG_BI_READER_ROLE TO USER SVC_POWERBI_REFRESH;

-- Network policy: publisher may only connect from the Databricks workspace's NAT egress IPs.
CREATE NETWORK POLICY IF NOT EXISTS NP_DATABRICKS_PUBLISHER ALLOWED_IP_LIST = ('203.0.113.10', '203.0.113.11');
ALTER USER SVC_DATABRICKS_PUBLISHER SET NETWORK_POLICY = NP_DATABRICKS_PUBLISHER;
