-- =============================================================================
-- GOLD replica tables (same columns as Databricks gold, Snowflake types).
-- STAGE.<TABLE>_CHANGES tables are created by the Spark connector on first write.
-- CLUSTER BY on the big facts keeps DirectQuery date filters pruning micro-partitions.
-- =============================================================================
USE ROLE SYSADMIN;
USE SCHEMA MFG_DW.GOLD;

CREATE TABLE IF NOT EXISTS DIM_DATE (
  DATE_KEY NUMBER(8) PRIMARY KEY, CALENDAR_DATE DATE, YEAR NUMBER(4), QUARTER NUMBER(1), MONTH NUMBER(2), MONTH_NAME VARCHAR,
  ISO_WEEK NUMBER(2), DAY_OF_WEEK NUMBER(1), DAY_NAME VARCHAR, IS_WEEKEND BOOLEAN, FISCAL_YEAR VARCHAR);

CREATE TABLE IF NOT EXISTS DIM_PLANT (
  PLANT_SK NUMBER(38) PRIMARY KEY, PLANT_ID VARCHAR, PLANT_NAME VARCHAR, CITY VARCHAR, COUNTRY_CODE VARCHAR(2), TIMEZONE VARCHAR,
  _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS DIM_SUPPLIER (
  SUPPLIER_SK NUMBER(38) PRIMARY KEY, SUPPLIER_ID VARCHAR, SUPPLIER_NAME VARCHAR, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS DIM_MACHINE (
  MACHINE_SK NUMBER(38) PRIMARY KEY, MACHINE_ID VARCHAR, MACHINE_NAME VARCHAR, PLANT_ID VARCHAR, LINE_ID VARCHAR, MACHINE_TYPE VARCHAR,
  MANUFACTURER VARCHAR, INSTALL_DATE DATE, STATUS VARCHAR, RATED_UNITS_PER_HOUR NUMBER, IS_SOURCE_DELETED BOOLEAN, ATTR_HASH VARCHAR,
  EFFECTIVE_FROM TIMESTAMP_NTZ, EFFECTIVE_TO TIMESTAMP_NTZ, IS_CURRENT BOOLEAN, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
  PRODUCT_SK NUMBER(38) PRIMARY KEY, PRODUCT_ID VARCHAR, SKU VARCHAR, PRODUCT_NAME VARCHAR, PRODUCT_FAMILY VARCHAR,
  UNIT_COST NUMBER(12,2), STD_CYCLE_TIME_SEC NUMBER, ATTR_HASH VARCHAR,
  EFFECTIVE_FROM TIMESTAMP_NTZ, EFFECTIVE_TO TIMESTAMP_NTZ, IS_CURRENT BOOLEAN, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS DIM_SHIFT (SHIFT_CODE VARCHAR PRIMARY KEY, SHIFT_NAME VARCHAR, START_HOUR NUMBER, END_HOUR NUMBER, CROSSES_MIDNIGHT BOOLEAN);
CREATE TABLE IF NOT EXISTS DIM_DEFECT_TYPE (DEFECT_CODE VARCHAR PRIMARY KEY, DEFECT_DESCRIPTION VARCHAR, DEFECT_CATEGORY VARCHAR, SEVERITY VARCHAR);

CREATE TABLE IF NOT EXISTS FACT_PRODUCTION_DAILY (
  DATE_KEY NUMBER(8), PRODUCTION_DATE DATE, PLANT_SK NUMBER(38), MACHINE_SK NUMBER(38), PRODUCT_SK NUMBER(38),
  MACHINE_ID VARCHAR, PRODUCT_ID VARCHAR, PRODUCTION_RUNS NUMBER, UNITS_PRODUCED NUMBER, UNITS_SCRAPPED NUMBER, UNITS_GOOD NUMBER,
  RUN_MINUTES NUMBER(12,2), IDEAL_UNITS NUMBER, INSPECTIONS NUMBER, SAMPLED_UNITS NUMBER, DEFECT_UNITS NUMBER, FAILED_INSPECTIONS NUMBER,
  _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ,
  CONSTRAINT PK_FACT_PRODUCTION_DAILY PRIMARY KEY (PRODUCTION_DATE, MACHINE_ID, PRODUCT_ID)
) CLUSTER BY (PRODUCTION_DATE);

CREATE TABLE IF NOT EXISTS FACT_MACHINE_DAILY (
  DATE_KEY NUMBER(8), PRODUCTION_DATE DATE, MACHINE_ID VARCHAR, RUN_MINUTES NUMBER(12,2), IDEAL_UNITS NUMBER, UNITS_PRODUCED NUMBER, UNITS_GOOD NUMBER,
  DOWNTIME_MINUTES NUMBER, BREAKDOWNS NUMBER, MACHINE_SK NUMBER(38), PLANT_SK NUMBER(38), ANOMALY_MINUTES NUMBER,
  AVG_TEMPERATURE_C NUMBER(8,2), MAX_VIBRATION_MM_S NUMBER(8,3), PLANNED_MINUTES NUMBER, AVAILABLE_MINUTES NUMBER,
  AVAILABILITY FLOAT, PERFORMANCE FLOAT, QUALITY FLOAT, OEE FLOAT, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ,
  CONSTRAINT PK_FACT_MACHINE_DAILY PRIMARY KEY (PRODUCTION_DATE, MACHINE_ID)
) CLUSTER BY (PRODUCTION_DATE);

CREATE TABLE IF NOT EXISTS FACT_QUALITY_INSPECTION (
  INSPECTION_ID NUMBER(38) PRIMARY KEY, DATE_KEY NUMBER(8), MACHINE_SK NUMBER(38), PRODUCT_SK NUMBER(38), DEFECT_CODE VARCHAR,
  PRODUCTION_LOG_ID NUMBER(38), INSPECTION_TS TIMESTAMP_NTZ, SAMPLE_SIZE NUMBER, DEFECT_COUNT NUMBER, INSPECTION_RESULT VARCHAR,
  INSPECTOR_ID VARCHAR, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ
) CLUSTER BY (DATE_KEY);

CREATE TABLE IF NOT EXISTS FACT_MAINTENANCE_EVENT (
  WORK_ORDER_ID VARCHAR PRIMARY KEY, REPORTED_DATE_KEY NUMBER(8), COMPLETED_DATE_KEY NUMBER(8), MACHINE_SK NUMBER(38), MACHINE_ID VARCHAR,
  WORK_TYPE VARCHAR, PRIORITY VARCHAR, STATUS VARCHAR, REPORTED_AT TIMESTAMP_NTZ, STARTED_AT TIMESTAMP_NTZ, COMPLETED_AT TIMESTAMP_NTZ,
  DOWNTIME_MINUTES NUMBER, RESPONSE_MINUTES NUMBER, REPAIR_MINUTES NUMBER, TECHNICIAN VARCHAR, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ);

CREATE TABLE IF NOT EXISTS FACT_SUPPLIER_DELIVERY (
  DELIVERY_ID VARCHAR PRIMARY KEY, DATE_KEY NUMBER(8), SUPPLIER_SK NUMBER(38), PLANT_SK NUMBER(38), MATERIAL_CODE VARCHAR, LOT_NUMBER VARCHAR,
  DELIVERED_QTY NUMBER, REJECTED_QTY NUMBER, ACCEPTED_QTY NUMBER, _PIPELINE_RUN_ID VARCHAR, _GOLD_UPDATED_TS TIMESTAMP_NTZ);

-- Publish audit inside Snowflake too (who loaded what, when): query history of the service user.
CREATE OR REPLACE VIEW MFG_DW.GOLD.VW_PUBLISH_HISTORY AS
SELECT start_time, end_time, query_type, rows_inserted, rows_updated, rows_deleted, execution_status, LEFT(query_text, 200) AS query_head
FROM TABLE(MFG_DW.INFORMATION_SCHEMA.QUERY_HISTORY_BY_USER(USER_NAME => 'SVC_DATABRICKS_PUBLISHER', RESULT_LIMIT => 1000))
WHERE query_type IN ('MERGE', 'TRUNCATE_TABLE');
