-- =============================================================================
-- REPORTING VIEWS — what Power BI consumes in DirectQuery (see docs/POWERBI_AND_SNOWFLAKE.md)
--
-- RULE OF THUMB USED ON THIS PROJECT
--   * Business logic that MANY consumers must agree on (OEE roll-up, scrap cost,
--     MTTR/MTBF) is defined ONCE, here in SQL: Power BI, Excel, finance SQL users and
--     data-science notebooks all get the same number.
--   * Small, pre-aggregated or "latest status" result sets -> DirectQuery on these views.
--   * Large, highly sliced, time-intelligence analysis -> Import semantic model on GOLD
--     star schema (powerbi/ project), NOT on these views.
-- =============================================================================
USE ROLE SYSADMIN;
USE SCHEMA MFG_DW.REPORTING;

-- 1. PLANT OEE DAILY — OEE must be re-derived from components when rolling up.
--    (Averaging machine OEE percentages is WRONG: a machine planned for 8h weighs the same as one planned for 24h.)
CREATE OR REPLACE VIEW VW_PLANT_OEE_DAILY AS
SELECT d.CALENDAR_DATE, d.YEAR, d.MONTH, p.PLANT_ID, p.PLANT_NAME,
       COUNT(DISTINCT f.MACHINE_ID)                                       AS MACHINES,
       SUM(f.PLANNED_MINUTES)                                             AS PLANNED_MINUTES,
       SUM(f.DOWNTIME_MINUTES)                                            AS DOWNTIME_MINUTES,
       SUM(f.UNITS_PRODUCED)                                              AS UNITS_PRODUCED,
       SUM(f.UNITS_GOOD)                                                  AS UNITS_GOOD,
       SUM(f.AVAILABLE_MINUTES) / NULLIF(SUM(f.PLANNED_MINUTES), 0)       AS AVAILABILITY,
       LEAST(1, SUM(f.UNITS_PRODUCED) / NULLIF(SUM(f.IDEAL_UNITS), 0))    AS PERFORMANCE,
       SUM(f.UNITS_GOOD) / NULLIF(SUM(f.UNITS_PRODUCED), 0)               AS QUALITY,
       (SUM(f.AVAILABLE_MINUTES) / NULLIF(SUM(f.PLANNED_MINUTES), 0))
         * LEAST(1, SUM(f.UNITS_PRODUCED) / NULLIF(SUM(f.IDEAL_UNITS), 0))
         * (SUM(f.UNITS_GOOD) / NULLIF(SUM(f.UNITS_PRODUCED), 0))         AS OEE
FROM MFG_DW.GOLD.FACT_MACHINE_DAILY f
JOIN MFG_DW.GOLD.DIM_DATE  d ON d.DATE_KEY = f.DATE_KEY
JOIN MFG_DW.GOLD.DIM_PLANT p ON p.PLANT_SK = f.PLANT_SK
GROUP BY d.CALENDAR_DATE, d.YEAR, d.MONTH, p.PLANT_ID, p.PLANT_NAME;

-- 2. SHOP-FLOOR STATUS (DirectQuery, auto page refresh 15 min) — today's machines + open work orders.
--    MES data is published HOURLY; with Import the report would lag until the next dataset refresh.
CREATE OR REPLACE VIEW VW_SHOPFLOOR_MACHINE_STATUS AS
SELECT m.PLANT_ID, m.LINE_ID, m.MACHINE_ID, m.MACHINE_NAME, m.MACHINE_TYPE, m.STATUS AS MES_STATUS,
       f.PRODUCTION_DATE, f.UNITS_PRODUCED, f.UNITS_GOOD, f.OEE, f.DOWNTIME_MINUTES, f.ANOMALY_MINUTES,
       f.AVG_TEMPERATURE_C, f.MAX_VIBRATION_MM_S,
       wo.OPEN_WORK_ORDERS, wo.OLDEST_OPEN_REPORTED_AT,
       CASE WHEN wo.OPEN_WORK_ORDERS > 0 THEN 'RED'
            WHEN f.ANOMALY_MINUTES > 30 OR f.OEE < 0.60 THEN 'AMBER'
            ELSE 'GREEN' END AS HEALTH_RAG,
       f._GOLD_UPDATED_TS AS DATA_AS_OF
FROM MFG_DW.GOLD.DIM_MACHINE m
LEFT JOIN MFG_DW.GOLD.FACT_MACHINE_DAILY f
       ON f.MACHINE_ID = m.MACHINE_ID AND f.PRODUCTION_DATE = CURRENT_DATE()
LEFT JOIN (SELECT MACHINE_ID, COUNT(*) AS OPEN_WORK_ORDERS, MIN(REPORTED_AT) AS OLDEST_OPEN_REPORTED_AT
           FROM MFG_DW.GOLD.FACT_MAINTENANCE_EVENT WHERE STATUS <> 'COMPLETED' GROUP BY MACHINE_ID) wo
       ON wo.MACHINE_ID = m.MACHINE_ID
WHERE m.IS_CURRENT AND m.MACHINE_SK <> -1 AND NOT m.IS_SOURCE_DELETED;

-- 3. SCRAP COST — uses the product's unit cost VALID ON THE PRODUCTION DAY (SCD2 point-in-time via PRODUCT_SK).
--    Finance reconciles this to the ERP cost ledger, so it must be ONE SQL definition.
CREATE OR REPLACE VIEW VW_SCRAP_COST_DAILY AS
SELECT f.PRODUCTION_DATE, p.PLANT_ID, f.MACHINE_ID, pr.PRODUCT_ID, pr.PRODUCT_NAME, pr.PRODUCT_FAMILY,
       f.UNITS_SCRAPPED, pr.UNIT_COST AS UNIT_COST_AS_OF_PRODUCTION,
       f.UNITS_SCRAPPED * pr.UNIT_COST AS SCRAP_COST
FROM MFG_DW.GOLD.FACT_PRODUCTION_DAILY f
JOIN MFG_DW.GOLD.DIM_PRODUCT pr ON pr.PRODUCT_SK = f.PRODUCT_SK
JOIN MFG_DW.GOLD.DIM_PLANT p ON p.PLANT_SK = f.PLANT_SK;

-- 4. EXECUTIVE MONTHLY KPIs (DirectQuery scorecard; < 100 rows per year).
CREATE OR REPLACE VIEW VW_EXEC_KPI_MONTHLY AS
WITH prod AS (
  SELECT DATE_TRUNC('MONTH', f.PRODUCTION_DATE) AS MONTH_START, p.PLANT_ID,
         SUM(f.UNITS_PRODUCED) AS UNITS_PRODUCED, SUM(f.UNITS_GOOD) AS UNITS_GOOD, SUM(f.UNITS_SCRAPPED) AS UNITS_SCRAPPED,
         SUM(f.SAMPLED_UNITS) AS SAMPLED_UNITS, SUM(f.DEFECT_UNITS) AS DEFECT_UNITS
  FROM MFG_DW.GOLD.FACT_PRODUCTION_DAILY f JOIN MFG_DW.GOLD.DIM_PLANT p ON p.PLANT_SK = f.PLANT_SK
  GROUP BY 1, 2),
oee AS (
  SELECT DATE_TRUNC('MONTH', CALENDAR_DATE) AS MONTH_START, PLANT_ID,
         SUM(PLANNED_MINUTES) AS PLANNED_MINUTES, SUM(DOWNTIME_MINUTES) AS DOWNTIME_MINUTES
  FROM VW_PLANT_OEE_DAILY GROUP BY 1, 2),
cost AS (
  SELECT DATE_TRUNC('MONTH', PRODUCTION_DATE) AS MONTH_START, PLANT_ID, SUM(SCRAP_COST) AS SCRAP_COST
  FROM VW_SCRAP_COST_DAILY GROUP BY 1, 2)
SELECT prod.MONTH_START, prod.PLANT_ID, prod.UNITS_PRODUCED, prod.UNITS_GOOD,
       prod.UNITS_SCRAPPED / NULLIF(prod.UNITS_PRODUCED, 0)   AS SCRAP_RATE,
       1 - prod.DEFECT_UNITS / NULLIF(prod.SAMPLED_UNITS, 0)  AS FIRST_PASS_YIELD,
       oee.DOWNTIME_MINUTES, 1 - oee.DOWNTIME_MINUTES / NULLIF(oee.PLANNED_MINUTES, 0) AS AVAILABILITY,
       cost.SCRAP_COST
FROM prod
LEFT JOIN oee  ON oee.MONTH_START = prod.MONTH_START AND oee.PLANT_ID = prod.PLANT_ID
LEFT JOIN cost ON cost.MONTH_START = prod.MONTH_START AND cost.PLANT_ID = prod.PLANT_ID;

-- 5. MAINTENANCE RELIABILITY — MTTR / MTBF per machine per month.
--    MTBF = operating minutes / number of breakdowns. MTTR = repair minutes / number of breakdowns.
CREATE OR REPLACE VIEW VW_MAINTENANCE_RELIABILITY_MONTHLY AS
WITH bd AS (
  SELECT MACHINE_ID, DATE_TRUNC('MONTH', REPORTED_AT) AS MONTH_START,
         COUNT_IF(WORK_TYPE = 'BREAKDOWN') AS BREAKDOWNS,
         SUM(IFF(WORK_TYPE = 'BREAKDOWN', REPAIR_MINUTES, 0)) AS BREAKDOWN_REPAIR_MINUTES,
         SUM(DOWNTIME_MINUTES) AS DOWNTIME_MINUTES
  FROM MFG_DW.GOLD.FACT_MAINTENANCE_EVENT WHERE STATUS = 'COMPLETED' GROUP BY 1, 2),
ops AS (
  SELECT MACHINE_ID, DATE_TRUNC('MONTH', PRODUCTION_DATE) AS MONTH_START, SUM(RUN_MINUTES) AS OPERATING_MINUTES
  FROM MFG_DW.GOLD.FACT_MACHINE_DAILY GROUP BY 1, 2)
SELECT ops.MACHINE_ID, ops.MONTH_START, ops.OPERATING_MINUTES,
       COALESCE(bd.BREAKDOWNS, 0) AS BREAKDOWNS, COALESCE(bd.DOWNTIME_MINUTES, 0) AS DOWNTIME_MINUTES,
       ops.OPERATING_MINUTES / NULLIF(bd.BREAKDOWNS, 0) / 60.0 AS MTBF_HOURS,
       bd.BREAKDOWN_REPAIR_MINUTES / NULLIF(bd.BREAKDOWNS, 0)  AS MTTR_MINUTES
FROM ops LEFT JOIN bd ON bd.MACHINE_ID = ops.MACHINE_ID AND bd.MONTH_START = ops.MONTH_START;

-- 6. DEFECT PARETO — top defect codes (quality engineers, DirectQuery drill from the import model via drill-through).
CREATE OR REPLACE VIEW VW_DEFECT_PARETO AS
SELECT d.CALENDAR_DATE, m.PLANT_ID, q.DEFECT_CODE, dt.DEFECT_CATEGORY, dt.SEVERITY,
       COUNT(*) AS INSPECTIONS_WITH_DEFECT, SUM(q.DEFECT_COUNT) AS DEFECT_UNITS
FROM MFG_DW.GOLD.FACT_QUALITY_INSPECTION q
JOIN MFG_DW.GOLD.DIM_DATE d ON d.DATE_KEY = q.DATE_KEY
JOIN MFG_DW.GOLD.DIM_MACHINE m ON m.MACHINE_SK = q.MACHINE_SK
LEFT JOIN MFG_DW.GOLD.DIM_DEFECT_TYPE dt ON dt.DEFECT_CODE = q.DEFECT_CODE
WHERE q.DEFECT_CODE <> 'NONE'
GROUP BY 1, 2, 3, 4, 5;

-- 7. SUPPLIER QUALITY — reject rate per supplier/material/month (procurement scorecard).
CREATE OR REPLACE VIEW VW_SUPPLIER_QUALITY_MONTHLY AS
SELECT DATE_TRUNC('MONTH', d.CALENDAR_DATE) AS MONTH_START, s.SUPPLIER_ID, s.SUPPLIER_NAME, f.MATERIAL_CODE, p.PLANT_ID,
       SUM(f.DELIVERED_QTY) AS DELIVERED_QTY, SUM(f.REJECTED_QTY) AS REJECTED_QTY,
       SUM(f.REJECTED_QTY) / NULLIF(SUM(f.DELIVERED_QTY), 0) AS REJECT_RATE
FROM MFG_DW.GOLD.FACT_SUPPLIER_DELIVERY f
JOIN MFG_DW.GOLD.DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
JOIN MFG_DW.GOLD.DIM_SUPPLIER s ON s.SUPPLIER_SK = f.SUPPLIER_SK
JOIN MFG_DW.GOLD.DIM_PLANT p ON p.PLANT_SK = f.PLANT_SK
GROUP BY 1, 2, 3, 4, 5;
